version: '2'
services:

   sppd-data-base:
      container_name: sppd-data-base
      build:
         context: .
      volumes:
         - ${PWD}:/app
      env_file:
         - .env
      environment:
         - GUNICORN_CMD_ARGS
      command: ['echo', 'hello']

   sppd-data:
      container_name: sppd-data
      extends: sppd-data-base
      build:
         context: .
      volumes:
         - '$PWD:/app'
      environment:
         - GUNICORN_CMD_ARGS=-w 4 -k gevent --reload
      ports:
         - 5000:5000
      command: sh bin/boot.sh